spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: testUser
    password: testPsw
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    include-message: always
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 9091